# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5404bac3697fde2b850205e1e4a48cea88b07229e23b0fcadf42ea1ff65c7abb91998eb4ec1d57ed0682ae3cf70468c866457ae00be79ddb491831dd46e7faf

test:
  secret_key_base: ec962ac2a76307c652ebe776ed400b37bdff6b6bd458d0b2fe6262f5db43640bcb6ad8047323c9d8c06ddd98d6de02bd912191888d68013fae27abb76f07c3b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
